Narail/Controllers/Admin/PanelController.cs
using Narail.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Narail.Controllers.Admin
{
    [Authorize]
    public class PanelController : Controller
    {
        KarapinarMedyaEntities1 db = new KarapinarMedyaEntities1();
        public ActionResult Index(int? id)
        {
           
            return View();
        }
    }
}

Narail/Controllers/Home/AboutController.cs
using Narail.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Narail.Controllers
{
   
    public class AboutController : Controller
    {
        KarapinarMedyaEntities1 db = new KarapinarMedyaEntities1();
        public ActionResult Index()
        {
            ViewBag.Title = "Karapınar Medya | Hakkımızda";
            Settings settings = db.Settings.Find(1);
            return View(settings);
        }
    }
}

Narail/Controllers/Home/ContactController.cs
using Narail.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Narail.Controllers
{
    public class ContactController : Controller
    {
        KarapinarMedyaEntities1 db = new KarapinarMedyaEntities1();
        public ActionResult Index()
        {
            ViewBag.Title = "Karapınar Medya | İletişim";
            return View();
        }
        public ActionResult Message(string nameSurname, string email,string phone,string subject,string message)
        {
                Feedback feedback = new Feedback();
                feedback.NameSurname = nameSurname;
                feedback.Email = email;
                feedback.Phone = phone;
                feedback.Subject = subject;
                feedback.Message = message;
                feedback.AddedDate = DateTime.Now;
                db.Feedback.Add(feedback);
                db.SaveChanges();
                return RedirectToAction("Index");       
        }

        public ActionResult ContactInformation()
        {
            Settings settings = db.Settings.Find(1);
            return View(settings);
        }
        public ActionResult SocialMedyaLayout()
        {
            Settings settings = db.Settings.Find(1);
            return View(settings);
        }

        public ActionResult SocialMedyaLayout2()
        {
            Settings settings = db.Settings.Find(1);
            return View(settings);
        }
        public ActionResult ContactLayout()
        {
            Settings settings = db.Settings.Find(1);
            return View(settings);
        }
        public ActionResult SiteLogo()
        {
            Settings settings = db.Settings.Find(1);
            return View(settings);
        }
        public ActionResult FooterLayout()
        {
            Settings settings = db.Settings.Find(1);
            return View(settings);
        }
        public ActionResult Seo()
        {
            Settings settings = db.Settings.Find(1);
            return View(settings);
        }
    }
}

Narail/Controllers/Home/LiveController.cs
using Narail.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Narail.Controllers.Home
{

    [ValidateInput(false)]
    public class LiveController : Controller
    {
        KarapinarMedyaEntities1 db = new KarapinarMedyaEntities1();
        public ActionResult Index()
        {
            Settings settings = db.Settings.Find(1);
            return View(settings);
        }
    }
}

Narail/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>


    <meta charset="UTF-8">
    <title>@(Html.Raw(ViewBag.Title))</title>
    <!-- mobile responsive meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    @Html.Action("Seo", "Contact")
    <link rel="stylesheet" href="@Url.Content("~/Content/Site/css/style.css")">
    <link rel="stylesheet" href="@Url.Content("~/Content/Site/css/responsive.css")">
    <link rel="apple-touch-icon" sizes="180x180" href="images/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" href="images/favicon/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="images/favicon/favicon-16x16.png" sizes="16x16">

    <script src="~/ckeditor/ckeditor.js"></script>
    <script src="~/ckfinder/ckfinder.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

</head>
<body>
    <div class="boxed_wrapper">
        <header class="top-bar" style="background:linear-gradient(to right,#bf953f,#fcf6ba,#b38728,#fbf5b7,#aa771c)">
            <div class="container">
                <div class="clearfix">
                    @Html.Action("ContactLayout", "Contact")
                    @Html.Action("SocialMedyaLayout2", "Contact")
                </div>
            </div>
        </header>
        <section class="mainmenu-area stricky">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        @Html.Action("SiteLogo", "Contact")
                    </div>

                    <div class="col-md-6 menu-column">
                        <nav class="main-menu">
                            <div style="background:#ffffff" class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <span style="background:#000000" class="icon-bar"></span>
                                    <span style="background:#000000" class="icon-bar"></span>
                                    <span style="background:#000000" class="icon-bar"></span>
                                    <span style="background:#000000" class="icon-bar"></span>
                                </button>
                            </div>
                            <div class="navbar-collapse collapse clearfix">
                                <ul class="navigation clearfix">

                                    <li>
                                        <a href="@Url.Action("","")">Anasayfa</a>

                                    </li>

                                    <li>
                                        <a href="@Url.Action("Index","About")">Hakkımızda</a> 
                                    </li>

                                    <li class="dropdown">
                                        <a href="#">Kategoriler</a>
                                        <ul>
                                            @Html.Action("LayoutIndex", "Category")
                                        </ul>
                                    </li>

                                    <li class="dropdown">
                                        <a href="@Url.Action("Index","Live")">CANLI YAYIN</a> 
                                    </li>

                                </ul>

                                <ul class="mobile-menu clearfix">

                                    <li>
                                        <a href="@Url.Action("Index","Home")">Anasayfa</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","Live")">Canlı Yayın</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","About")">Hakkımızda</a>
                                    </li>



                                    <li class="dropdown">
                                        <a href="#">Kategoriler</a>
                                        <ul>
                                            @Html.Action("LayoutIndex", "Category")
                                        </ul>
                                    </li>

                                    <li>
                                        <a href="@Url.Action("Index","Contact")">İletişim</a>
                                    </li>

                                </ul>
                            </div>
                        </nav>
                    </div>

                    <div class="col-md-2">
                        <div class="right-column">
                            <div class="right-area">
                                <div class="link-btn4 float_right">
                                    <a href="@Url.Action("Index","Contact")" class="btn-style-one" style=" border: 1px black; background: linear-gradient(to right,#bf953f,#fcf6ba,#b38728,#fbf5b7,#aa771c)">İletişim</a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>
        @RenderBody()

        @RenderSection("scripts", required: false)
        <footer class="main-footer">
            <!--Widgets Section-->
            <div class="widgets-section">
                <div class="container">
                    <div class="row">
                        <!--Big Column-->
                        <div class="big-column col-md-6 col-sm-12 col-xs-12">
                            <div class="row clearfix">

                                <!--Footer Column-->
                                <div class="footer-column col-md-6 col-sm-6 col-xs-12">
                                    <div class="footer-widget about-widget">
                                        <figure class="footer-logo"><a href="index.html"><img src="images/logo/KarapinarMedya-1.png" alt=""></a></figure>

                                        <div class="widget-content">
                                            @Html.Action("FooterLayout", "Contact")

                                            <ul class="social">
                                                @Html.Action("SocialMedyaLayout", "Contact")
                                            </ul>
                                        </div>
                                    </div>
                                </div>

                                <!--Footer Column-->


                            </div>
                        </div>

                        <!--Big Column-->
                        <div class="big-column col-md-6 col-sm-12 col-xs-12">
                            <div class="row clearfix">

                                <!--Footer Column-->
                                <div class="footer-column col-md-6 col-sm-6 col-xs-12">
                                    <div class="footer-widget links-widget">
                                        <div class="section-title">
                                            <h3>Hızlı Bağlantılar</h3>
                                        </div>
                                        <div class="widget-content">
                                            <ul class="list">
                                                <li><a href="@Url.Action("Index", "Home")">Anasayfa</a></li>

                                                <li><a href="@Url.Action("Index", "About")">Hakkımızda</a></li>
                                                <li><a href="@Url.Action("Index", "Live")">Canlı Yayın</a></li>

                                                <li><a href="@Url.Action("Index", "Contact")">İletişim</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>


                                <!--Footer Column-->
                                <div class="footer-column col-md-6 col-sm-6 col-xs-12">
                                    <div class="footer-widget contact-widget">
                                       

                                    </div>
                                </div>


                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <!--Footer Bottom-->
            <div class="footer-bottom">
                <div class="container">
                    <div class="pull-left copy-text">
                        <p>Telif Hakkı © 2022 Tüm Hakları Saklıdır <a href="#"> Karapınar Medya.</a></p>

                    </div><!-- /.pull-right -->
                    <div class="pull-right get-text">
                        <ul>


                            <li><a href=@Url.Action("Index","Login")> Giriş Yap</a></li>
                        </ul>
                    </div><!-- /.pull-left -->
                </div><!-- /.container -->
            </div>
        </footer>
        <!-- Scroll Top Button -->
        <button style="background:#000000" class="scroll-top tran3s color2_bg">
            <span class="fa fa-angle-up"></span>
        </button>
        <!-- pre loader  -->
        <div class="preloader"></div>
        <!-- jQuery js -->
        <script src="@Url.Content("~/Content/Site/js/jquery.js")"></script>
        <!-- bootstrap js -->
        <script src="@Url.Content("~/Content/Site/js/bootstrap.min.js")"></script>
        <!-- jQuery ui js -->
        <script src="@Url.Content("~/Content/Site/js/jquery-ui.js")"></script>
        <!-- owl carousel js -->
        <script src="@Url.Content("~/Content/Site/js/owl.carousel.min.js")"></script>
        <!-- jQuery validation -->
        <script src="@Url.Content("~/Content/Site/js/jquery.validate.min.js")"></script>
        <!-- google map -->
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRvBPo3-t31YFk588DpMYS6EqKf-oGBSI"></script>
        <script src="@Url.Content("~/Content/Site/js/gmap.js")"></script>
        <!-- mixit up -->
        <script src="@Url.Content("~/Content/Site/js/wow.js")"></script>
        <script src="@Url.Content("~/Content/Site/js/jquery.mixitup.min.js")"></script>
        <script src="@Url.Content("~/Content/Site/js/jquery.fitvids.js")"></script>
        <script src="@Url.Content("~/Content/Site/js/bootstrap-select.min.js")"></script>
        <!-- revolution slider js -->
        <script src="@Url.Content("~/Content/Site/assets/revolution/js/jquery.themepunch.tools.min.js")"></script>
        <script src="@Url.Content("~/Content/Site/assets/revolution/js/jquery.themepunch.revolution.min.js")"></script>
        <script src="@Url.Content("~/Content/Site/assets/revolution/js/extensions/revolution.extension.actions.min.js")"></script>
        <script src="@Url.Content("~/Content/Site/assets/revolution/js/extensions/revolution.extension.carousel.min.js")"></script>
        <script src="@Url.Content("~/Content/Site/assets/revolution/js/extensions/revolution.extension.kenburn.min.js")"></script>
        <script src="@Url.Content("~/Content/Site/assets/revolution/js/extensions/revolution.extension.layeranimation.min.js")"></script>
        <script src="@Url.Content("~/Content/Site/assets/revolution/js/extensions/revolution.extension.migration.min.js")"></script>
        <script src="@Url.Content("~/Content/Site/assets/revolution/js/extensions/revolution.extension.navigation.min.js")"></script>
        <script src="@Url.Content("~/Content/Site/assets/revolution/js/extensions/revolution.extension.parallax.min.js")"></script>
        <script src="@Url.Content("~/Content/Site/assets/revolution/js/extensions/revolution.extension.slideanims.min.js")"></script>
        <script src="@Url.Content("~/Content/Site/assets/revolution/js/extensions/revolution.extension.video.min.js")"></script>
        <!-- fancy box -->
        <script src="@Url.Content("~/Content/Site/js/jquery.fancybox.pack.js")"></script>
        <script src="@Url.Content("~/Content/Site/js/jquery.polyglot.language.switcher.js")"></script>
        <script src="@Url.Content("~/Content/Site/js/nouislider.js")"></script>
        <script src="@Url.Content("~/Content/Site/js/jquery.bootstrap-touchspin.js")"></script>
        <script src="@Url.Content("~/Content/Site/js/SmoothScroll.js")"></script>
        <script src="@Url.Content("~/Content/Site/js/jquery.appear.js")"></script>
        <script src="@Url.Content("~/Content/Site/js/jquery.countTo.js")"></script>
        <script src="@Url.Content("~/Content/Site/js/jquery.flexslider.js")"></script>
        <script src="@Url.Content("~/Content/Site/js/imagezoom.js")"></script>
        <script id="map-script" src="@Url.Content("~/Content/Site/js/default-map.js")"></script>
        <script src="@Url.Content("~/Content/Site/js/custom.js")"></script>
    </div>

</body>
</html>

Narail/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Karapınar Medya | Yönetim Paneli</title>
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <link href="@Url.Content("~/Content/Admin/plugins/bootstrap/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/Admin/css/style.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/Admin/css/themes/all-themes.css")" rel="stylesheet" />

    <script src="@Url.Content("~/ckeditor/ckeditor.js")"></script>
    <script src="@Url.Content("~/ckeditor/ckfinder.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>

</head>
<body class="theme-purple">
    @Html.Partial("_TopBar")
    <section>
        @Html.Partial("_LeftsideBar")

        @Html.Partial("_RightsideBar")
    </section>
    <section class="content">
        <div class="container-fluid">
            @RenderBody()
        </div>
    </section>
    <script src="@Url.Content("~/Content/Admin/plugins/jquery/jquery.min.js")"></script>
    <script src="@Url.Content("~/Content/Admin/plugins/bootstrap/js/bootstrap.js")"></script>
    <script src="@Url.Content("~/Content/Admin/plugins/bootstrap-select/js/bootstrap-select.js")"></script>
    <script src="@Url.Content("~/Content/Admin/plugins/jquery-slimscroll/jquery.slimscroll.js")"></script>
    <script src="@Url.Content("~/Content/Admin/plugins/node-waves/waves.js")"></script>
    <script src="@Url.Content("~/Content/Admin/plugins/jquery-countto/jquery.countTo.js")"></script>
    <script src="@Url.Content("~/Content/Admin/plugins/raphael/raphael.min.js")"></script>
    <script src="@Url.Content("~/Content/Admin/plugins/morrisjs/morris.js")"></script>
    <script src="@Url.Content("~/Content/Admin/plugins/chartjs/Chart.bundle.js")"></script>
    <script src="@Url.Content("~/Content/Admin/plugins/jquery-sparkline/jquery.sparkline.js")"></script>
    <script src="@Url.Content("~/Content/Admin/js/admin.js")"></script>
    <script src="@Url.Content("~/Content/Admin/js/pages/index.js")"></script>
    <script src="@Url.Content("~/Content/Admin/js/demo.js")"></script>
</body>

</html>

Narail/Views/Shared/_LeftsideBar.cshtml
<aside id="leftsidebar" class="sidebar">
    <!-- User Info -->
    <div class="user-info">
        <div class="image">

            @if (@Session["Image"] == null)
            {
                <img src="~/Content/Admin/images/user.png" width="48" height="48" alt="User" />
            }
            else
            {
                <img src=@Session["Image"] width="48" height="48" alt="User" />
            }


        </div>
        <div class="info-container">
            <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@Session["NameSurname"]</div>
            <div class="email">@Session["Email"]</div>

        </div>
    </div>
    <!-- #User Info -->
    <!-- Menu -->
    <div class="menu">
        <ul class="list">
            <li class="header">SİTE İŞLEMLERİ</li>
            <li class="active">
                <a href="@Url.Action("Index","Panel")">
                    <i class="material-icons col-blue">home</i>
                    <span style="color: #000000">Panel</span>
                </a>
            </li>



            <li>
                <a href="javascript:void(0);" class="menu-toggle">
                    <i class="material-icons col-blue">newspaper</i>
                    <span>Haber Yönetimi</span>
                </a>
                <ul class="ml-menu">
                    <li class="active">
                        <a href="@Url.Action("Index","NewsAdd")">Haberler</a>
                    </li>
                    <li class="active">
                        <a href="@Url.Action("Create","NewsAdd")" )">Haber Ekle</a>
                    </li>

                </ul>
            </li>
            <li class="active">
                <a href="@Url.Action("Index","Feedback")">
                    <i class="material-icons col-blue">message</i>
                    <span style="color: #000000">Mesajlar</span>
                </a>
            </li>

         

            <li>
                <a href="javascript:void(0);" class="menu-toggle">
                    <i class="material-icons col-blue">bookmark</i>
                    <span>Kategori Yönetimi</span>
                </a>
                <ul class="ml-menu">
                    <li class="active">
                        <a href="@Url.Action("Index","Category")">Kategoriler</a>
                    </li>
                    <li class="active">
                        <a href="@Url.Action("Create","Category")" )">Kategori Ekle</a>
                    </li>

                </ul>
            </li>

            @if (Session["Admin"] == "Admin")
            {
        <li>
            <a href="javascript:void(0);" class="menu-toggle">
                <i class="material-icons col-blue">edit</i>
                <span>Yazar Yönetimi</span>
            </a>
            <ul class="ml-menu">
                <li class="active">
                    <a href="@Url.Action("Index","AuthorAdmin")">Yazarlar</a>
                </li>
                <li class="active">
                    <a href="@Url.Action("Create","AuthorAdmin")">Yazar Ekle</a>
                </li>

            </ul>
        </li>}

            @if (Session["Admin"] == "Admin")
            {
        <li>
            <a href="javascript:void(0);" class="menu-toggle">
                <i class="material-icons col-blue">settings</i>
                <span>Ayarlar</span>
            </a>
            <ul class="ml-menu">

                <li class="active">
                    <a href="@Url.Action("ContactSettings","Settings")">İletişim Ayarları</a>
                </li>
                <li class="active">
                    <a href="@Url.Action("SocialMedia","Settings")">Sosyal Medya Ayarları</a>
                </li>
                <li class="active">
                    <a href="@Url.Action("Youtube","Settings")">Youtube Canlı Yayın</a>
                </li>
                <li class="active">
                    <a href="@Url.Action("CompanySettings","Settings")">Şirket Ayarları</a>
                </li>
                <li class="active">
                    <a href="@Url.Action("SeoSettings","Settings")">Seo Ayarları</a>
                </li>
               

            </ul>
        </li>}


            <li class="header">HIZLI AYARLAR</li>

            <li>
                <a href="@Url.Action("Youtube","Settings")">
                    <i class="material-icons col-amber">donut_large</i>
                    <span>Youtube Canlı Yayın</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("SocialMedia","Settings")">
                    <i class="material-icons col-green">donut_large</i>
                    <span>Sosyal Medya Ayarları</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("ContactSettings","Settings")">
                    <i class="material-icons col-red">donut_large</i>
                    <span>İletişim Ayarları</span>
                </a>
            </li>

        </ul>
    </div>
    <!-- #Menu -->
    <!-- Footer -->
    <div class="legal">
        <div class="copyright">
            &copy; 2022 <a style="color:#0094ff" href="javascript:void(0);">Karapınar Medya</a>.
        </div>
        <div class="version">
            <b>Version: </b> 1.0.3
        </div>
    </div>
    <!-- #Footer -->
</aside>

Narail/Views/Shared/_TopBar.cshtml
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
        <p>Lütfen Bekleyin...</p>
    </div>
</div>
<div class="overlay"></div>

<nav style="background:#0f6cff" class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="@Url.Action("Index","Panel")">YÖNETİM PANELİ</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <!-- Call Search -->

                

                <li><a href="@Url.Action("Logout","Login")"><i class="material-icons">exit_to_app</i></a></li>

               
            </ul>
        </div>
    </div>
</nav>